import { askGemini } from "../utils/gemini.js";
import {
  searchArxiv,
  searchHuggingFace,
  searchAINews,
} from "./searchService.js";
import { createClient } from "@supabase/supabase-js";

function getSupabase() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_KEY
  );
}

function cleanGeminiJson(raw) {
  return raw
    .replace(/```json/g, "")
    .replace(/```/g, "")
    .trim();
}

function safeJsonParse(text) {
  try {
    return JSON.parse(text);
  } catch {
    const start = text.indexOf("{");
    const end = text.lastIndexOf("}");

    if (start !== -1 && end !== -1) {
      return JSON.parse(text.slice(start, end + 1));
    }

    throw new Error("Invalid JSON returned from Gemini");
  }
}

export async function runAgentResearch(
  userId,
  topic,
  language = "en",
  options = {}
) {
  const supabase = getSupabase();

  const autoGenerated = options.autoGenerated === true;
  const isUnread = options.isUnread === true;

  console.log("Agent searching for:", topic);
  console.log("Report language:", language);
  console.log("Auto generated:", autoGenerated);

  const isArabic = language === "ar";
  const reportLanguage = isArabic ? "Arabic" : "English";

  const [arxivResults, hfResults, newsResults] = await Promise.all([
    searchArxiv(topic),
    searchHuggingFace(topic),
    searchAINews(topic),
  ]);

  const allResults = [...arxivResults, ...hfResults, ...newsResults];

  const arabicRules = `
CRITICAL LANGUAGE RULES:
- Write the entire report in Arabic.
- All JSON text values must be Arabic unless they are paper titles, project names, model names, source names, URLs, or technical acronyms.
- The "sections.name" values must be exactly:
  1. "الأوراق البحثية"
  2. "أحدث المشاريع"
  3. "أخبار الذكاء الاصطناعي"
- Use Arabic for:
  title
  shortTitle
  executiveSummary
  whyItMatters
  summary
  whyItMatters inside each item
  keyInsights
  technicalChallenges
  futureDirections
  recommendedTopics
- Keep technical terms such as LLMs, RAG, MCP, AI Agents, Transformers, GPT, Gemini, arXiv, Hugging Face in English when needed.
`;

  const englishRules = `
CRITICAL LANGUAGE RULES:
- Write the entire report in English.
- The "sections.name" values must be exactly:
  1. "Research Papers"
  2. "Latest Projects"
  3. "AI News"
`;

  const reportPrompt = `
You are TraceFlow, an AI research agent specialized in artificial intelligence.

The user is interested in:
"${topic}"

The selected user interface language is:
"${reportLanguage}"

You are given real search results from arXiv, Hugging Face, and AI news sources.
Use ONLY the provided results. Do not invent papers, links, or projects.

Search results:
${JSON.stringify(allResults, null, 2)}

Create a deep, structured research report in ${reportLanguage}.

${isArabic ? arabicRules : englishRules}

The report must include:
1. A clear full title
2. A short title for the library book
3. Executive summary of 5-7 sentences
4. Why this topic matters now
5. Research papers section
6. Latest projects section
7. AI news section
8. Key insights
9. Technical challenges
10. Future directions
11. Recommended next topics

Short title rules:
- Maximum 2 to 4 words.
- It should summarize the report clearly.
- Do not include words like "Report", "Research", or "TraceFlow".
- If the selected language is Arabic, shortTitle must be Arabic.
- If the selected language is English, shortTitle must be English.
- Keep common technical acronyms in English when needed.

For every item, include:
- title
- source
- link
- detailed summary
- why it matters
- technical keywords

Return ONLY valid JSON in this exact structure:
{
  "title": "",
  "shortTitle": "",
  "executiveSummary": "",
  "whyItMatters": "",
  "sections": [
    {
      "name": "",
      "items": [
        {
          "title": "",
          "source": "",
          "link": "",
          "summary": "",
          "whyItMatters": "",
          "technicalKeywords": []
        }
      ]
    },
    {
      "name": "",
      "items": [
        {
          "title": "",
          "source": "",
          "link": "",
          "summary": "",
          "whyItMatters": "",
          "technicalKeywords": []
        }
      ]
    },
    {
      "name": "",
      "items": [
        {
          "title": "",
          "source": "",
          "link": "",
          "summary": "",
          "whyItMatters": "",
          "technicalKeywords": []
        }
      ]
    }
  ],
  "keyInsights": [],
  "technicalChallenges": [],
  "futureDirections": [],
  "recommendedTopics": []
}
`;

  const rawReport = await askGemini(reportPrompt);
  const cleanJson = cleanGeminiJson(rawReport);
  const report = safeJsonParse(cleanJson);

  report.autoGenerated = autoGenerated;
  report.isUnread = isUnread;

  const { data: savedReport, error } = await supabase
    .from("research_library")
    .insert({
      user_id: userId,
      topic,
      report,
      created_at: new Date().toISOString(),
    })
    .select()
    .single();

  if (error) throw new Error("Supabase error: " + error.message);

  const suggestions = await generateSuggestions(userId, topic, language);

  return { report: savedReport, suggestions };
}

export async function generateSuggestions(userId, newTopic, language = "en") {
  const supabase = getSupabase();

  const isArabic = language === "ar";
  const suggestionLanguage = isArabic ? "Arabic" : "English";

  const { data: history } = await supabase
    .from("research_library")
    .select("topic")
    .eq("user_id", userId);

  const allTopics = history?.map((h) => h.topic) || [];
  allTopics.push(newTopic);

  const prompt = `
The user has researched these AI topics:
${allTopics.join(", ")}

Generate 2 specific related AI topics that are useful as next research directions.
Avoid generic topics.
Avoid repeating any topic already researched.

Write the suggestions in ${suggestionLanguage}.
${
  isArabic
    ? "Use Arabic wording, but keep technical terms like RAG, LLMs, MCP, AI Agents in English when needed."
    : "Use English wording."
}

Return ONLY valid JSON:
{
  "suggestions": ["", ""]
}
`;

  const raw = await askGemini(prompt);
  const clean = cleanGeminiJson(raw);
  const { suggestions } = safeJsonParse(clean);

  await supabase.from("suggestions").upsert(
    {
      user_id: userId,
      topics: suggestions,
      based_on: allTopics,
      updated_at: new Date().toISOString(),
    },
    { onConflict: "user_id" }
  );

  return suggestions;
}

export async function getUserLibrary(userId) {
  const supabase = getSupabase();

  const { data: library, error } = await supabase
    .from("research_library")
    .select("id, topic, report, created_at")
    .eq("user_id", userId)
    .order("created_at", { ascending: false });

  if (error) throw new Error(error.message);

  const { data: suggestions } = await supabase
    .from("suggestions")
    .select("topics")
    .eq("user_id", userId)
    .single();

  return {
    library: library || [],
    suggestions: suggestions?.topics || [],
  };
}

export async function markReportAsRead(reportId) {
  const supabase = getSupabase();

  const { data: existingReport, error: fetchError } = await supabase
    .from("research_library")
    .select("report")
    .eq("id", reportId)
    .single();

  if (fetchError) throw new Error(fetchError.message);

  const updatedReport = {
    ...existingReport.report,
    isUnread: false,
  };

  const { data, error } = await supabase
    .from("research_library")
    .update({
      report: updatedReport,
    })
    .eq("id", reportId)
    .select()
    .single();

  if (error) throw new Error(error.message);

  return data;
}

async function getDailyTopicForUser(userId) {
  const supabase = getSupabase();

  const { data: history, error } = await supabase
    .from("research_library")
    .select("topic")
    .eq("user_id", userId)
    .order("created_at", { ascending: false })
    .limit(10);

  if (error) throw new Error(error.message);

  const topics = history?.map((item) => item.topic) || [];

  if (topics.length === 0) return null;

  const prompt = `
The user has previously researched these AI topics:
${topics.join(", ")}

Generate exactly ONE new AI research topic for today's automatic report.

Rules:
- It must be related to the user's previous interests.
- It must be specific, not generic.
- It must not repeat any previous topic.
- Return ONLY valid JSON.

JSON structure:
{
  "topic": ""
}
`;

  const raw = await askGemini(prompt);
  const clean = cleanGeminiJson(raw);
  const result = safeJsonParse(clean);

  return result.topic;
}

export async function runDailyAgent() {
  const supabase = getSupabase();

  const { data: users, error } = await supabase
    .from("research_library")
    .select("user_id");

  if (error) throw new Error(error.message);

  const uniqueUserIds = [...new Set((users || []).map((item) => item.user_id))];

  const results = [];

  for (const userId of uniqueUserIds) {
    try {
      const topic = await getDailyTopicForUser(userId);

      if (!topic) {
        results.push({
          userId,
          status: "skipped",
          reason: "No previous topics",
        });
        continue;
      }

      const created = await runAgentResearch(userId, topic, "en", {
        autoGenerated: true,
        isUnread: true,
      });

      results.push({
        userId,
        status: "created",
        topic,
        reportId: created.report?.id,
      });
    } catch (error) {
      results.push({
        userId,
        status: "failed",
        error: error.message,
      });
    }
  }

  return {
    totalUsers: uniqueUserIds.length,
    results,
  };
}