import { useState } from "react";
import "./Library.css";

import outputShape from "../assets/output.svg";
import exploreShape from "../assets/explore.svg";

function chunkArray(array, size) {
  const chunks = [];

  for (let i = 0; i < array.length; i += size) {
    chunks.push(array.slice(i, i + size));
  }

  return chunks;
}

function Library({
  language = "en",
  reports = [],
  suggestions = [],
  onOpenReport,
  onGenerateFromSuggestion,
}) {
  const [showSuggestions, setShowSuggestions] = useState(false);

  const isArabic = language === "ar";
  const shelves = chunkArray(reports, 4);
  const visibleSuggestions = suggestions.slice(0, 2);

  if (showSuggestions) {
    return (
      <main className="explore-page" dir={isArabic ? "rtl" : "ltr"}>
        <div className="explore-wrapper">
          <img className="explore-shape" src={exploreShape} alt="" />

          <div className="explore-content">
            <h1>
              {isArabic ? "اختر بحثك التالي" : "Choose your next research"}
            </h1>

            <div className="explore-options">
              {visibleSuggestions.length > 0 ? (
                visibleSuggestions.map((topic, index) => (
                  <button
                    key={index}
                    className="explore-topic-btn"
                    type="button"
                    onClick={() => onGenerateFromSuggestion(topic)}
                  >
                    {topic}
                  </button>
                ))
              ) : (
                <p className="explore-empty">
                  {isArabic
                    ? "لا توجد اقتراحات حاليًا"
                    : "No suggestions available yet"}
                </p>
              )}
            </div>

            <button
              className="explore-back-btn"
              type="button"
              onClick={() => setShowSuggestions(false)}
            >
              {isArabic ? "رجوع" : "Back"}
            </button>
          </div>
        </div>
      </main>
    );
  }

  return (
    <main className="library-page" dir={isArabic ? "rtl" : "ltr"}>
      <h1 className="library-title">
        {isArabic ? "مكتبتك" : "Your Library"}
      </h1>

      {reports.length === 0 && (
        <p className="library-status">
          {isArabic ? "لا توجد تقارير حتى الآن" : "No reports yet"}
        </p>
      )}

      <div className="library-shelves">
        {shelves.map((shelf, shelfIndex) => (
          <div className="library-shelf-block" key={shelfIndex}>
            <div className="library-books-row">
              {shelf.map((item) => (
                <button
                  className="library-book-btn"
                  key={item.id}
                  onClick={() => onOpenReport(item)}
                  type="button"
                  title={item.report?.title || item.topic}
                >
                  <img
                    className="library-book"
                    src={outputShape}
                    alt="report"
                  />

                  {item.report?.autoGenerated &&
                    item.report?.isUnread && (
                      <span className="library-book-new">
                        {isArabic ? "جديد" : "NEW"}
                      </span>
                    )}

                  <span className="library-book-title">
                    {item.report?.shortTitle ||
                      item.topic ||
                      "Research"}
                  </span>
                </button>
              ))}
            </div>

            <div className="library-shelf"></div>
          </div>
        ))}
      </div>

      <button
        className="library-btn"
        type="button"
        onClick={() => setShowSuggestions(true)}
      >
        {isArabic
          ? "اكتشف مواضيع مشابهة"
          : "Explore Similar Topics"}
      </button>
    </main>
  );
}

export default Library;