import { useEffect, useState } from "react";
import { supabase } from "./lib/supabase";

import Welcome from "./pages/Welcome";
import Language from "./pages/Language";
import Login from "./pages/Login";
import Interests from "./pages/Interests";
import Loading from "./pages/Loading";
import Report from "./pages/Report";
import Library from "./pages/Library";

const API_URL = "https://traceflow-backend-fhou.onrender.com";

function App() {
  const [page, setPage] = useState("welcome");
  const [language, setLanguage] = useState(
    localStorage.getItem("traceflow_language") || "en"
  );
  const [user, setUser] = useState(null);
  const [hasInterests, setHasInterests] = useState(false);
  const [researchResult, setResearchResult] = useState(null);
  const [libraryReports, setLibraryReports] = useState([]);
  const [suggestions, setSuggestions] = useState([]);
  const [error, setError] = useState("");

  async function loadLibrary(currentUser) {
    if (!currentUser) return;

    try {
      const response = await fetch(
        `${API_URL}/api/agent/library/${currentUser.id}`
      );

      const result = await response.json();

      if (!response.ok) {
        throw new Error(result.error || "Failed to load library");
      }

      setLibraryReports(result.data.library || []);
      setSuggestions(result.data.suggestions || []);
    } catch (err) {
      console.error(err);
      setError(err.message);
    }
  }

  useEffect(() => {
    async function getSession() {
      const { data } = await supabase.auth.getSession();
      const currentUser = data.session?.user ?? null;

      setUser(currentUser);

      if (currentUser) {
        const savedInterest = localStorage.getItem(
          "traceflow_interest_" + currentUser.id
        );

        setHasInterests(!!savedInterest);
      }
    }

    getSession();

    const { data: listener } = supabase.auth.onAuthStateChange(
      (_event, session) => {
        const currentUser = session?.user ?? null;

        setUser(currentUser);

        if (currentUser) {
          const savedInterest = localStorage.getItem(
            "traceflow_interest_" + currentUser.id
          );

          setHasInterests(!!savedInterest);
        } else {
          setHasInterests(false);
        }
      }
    );

    return () => {
      listener.subscription.unsubscribe();
    };
  }, []);

  const generateReport = async (topic, goTo = "report") => {
    if (!user) return;

    setPage("loading");
    setError("");

    try {
      const response = await fetch(`${API_URL}/api/agent/research`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          userId: user.id,
          topic,
          language,
        }),
      });

      const result = await response.json();

      if (!response.ok) {
        throw new Error(result.error || "Agent Error");
      }

      setResearchResult(result.data);
      await loadLibrary(user);

      setPage(goTo);
    } catch (err) {
      console.error(err);
      setError(err.message);
      setPage("report");
    }
  };

  const handleSaveInterest = async (interest) => {
    if (!user) return;

    localStorage.setItem("traceflow_interest_" + user.id, interest);
    setHasInterests(true);

    await generateReport(interest, "report");
  };

  const handleOpenReport = async (reportItem) => {
    let openedReport = reportItem;

    if (reportItem.report?.autoGenerated && reportItem.report?.isUnread) {
      try {
        const response = await fetch(
          `${API_URL}/api/agent/read/${reportItem.id}`,
          {
            method: "POST",
          }
        );

        const result = await response.json();

        if (response.ok && result.data) {
          openedReport = result.data;

          setLibraryReports((prev) =>
            prev.map((item) =>
              item.id === reportItem.id ? result.data : item
            )
          );
        }
      } catch (err) {
        console.error("Failed to mark report as read:", err);
      }
    }

    setResearchResult({
      report: openedReport,
      suggestions,
    });

    setPage("report");
  };

  const handleGoToLibrary = async () => {
    await loadLibrary(user);
    setPage("library");
  };

  const handleGenerateFromSuggestion = async (topic) => {
    await generateReport(topic, "library");
    await loadLibrary(user);
  };

  const handleLogout = async () => {
    await supabase.auth.signOut();

    if (user) {
      localStorage.removeItem("traceflow_interest_" + user.id);
    }

    setUser(null);
    setHasInterests(false);
    setResearchResult(null);
    setLibraryReports([]);
    setSuggestions([]);
    setError("");
    setPage("welcome");
  };

  if (page === "loading") {
    return <Loading language={language} />;
  }

  if (user && !hasInterests) {
    return <Interests onComplete={handleSaveInterest} language={language} />;
  }

  if (user && page === "library") {
    return (
      <Library
        language={language}
        reports={libraryReports}
        suggestions={suggestions}
        onOpenReport={handleOpenReport}
        onGenerateFromSuggestion={handleGenerateFromSuggestion}
      />
    );
  }

  if (user && page === "report") {
    if (error) {
      return (
        <main
          dir={language === "ar" ? "rtl" : "ltr"}
          style={{
            width: "100vw",
            height: "100vh",
            background: "#2d3235",
            color: "#ff8a8a",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            textAlign: "center",
            padding: "30px",
            fontFamily: "Arial",
          }}
        >
          <div>
            <h1>{language === "ar" ? "تقرير TraceFlow" : "TraceFlow Report"}</h1>
            <p>{error}</p>
          </div>
        </main>
      );
    }

    return (
      <Report
        researchResult={researchResult}
        language={language}
        onGoToLibrary={handleGoToLibrary}
      />
    );
  }

  if (user && hasInterests && !researchResult) {
    return (
      <main
        dir={language === "ar" ? "rtl" : "ltr"}
        style={{
          width: "100vw",
          height: "100vh",
          background: "#2d3235",
          color: "white",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          fontFamily: "Arial",
        }}
      >
        <p>{user.email}</p>
      </main>
    );
  }

  if (page === "language") {
    return (
      <Language
        onSelectLanguage={(selectedLanguage) => {
          setLanguage(selectedLanguage);
          localStorage.setItem("traceflow_language", selectedLanguage);
          setPage("login");
        }}
      />
    );
  }

  if (page === "login") {
    return <Login language={language} />;
  }

  return <Welcome onGetStarted={() => setPage("language")} />;
}

export default App;